INSERT INTO gateway_routes (
    id, category, path_patterns, methods, target_uri, strip_prefix,
    rewrite_regex, rewrite_replacement, route_order, enabled,
    authentication_types, required_roles, required_scopes, signing_required,
    connect_timeout_ms, response_timeout_ms, retry_enabled, retry_max_attempts,
    retry_methods, circuit_breaker_enabled, circuit_breaker_name, audit_mode,
    version, created_at, updated_at
) VALUES
('user-public-profile', 'PUBLIC', '/api/v1/public/users/*', 'GET', 'http://user-service:8081', 0,
 '/api/v1/public/users/(?<id>[^/]+)', '/internal/v1/users/${id}/public', 100, TRUE,
 'NONE', '', '', FALSE, 1000, 3000, FALSE, 1, '', TRUE, 'user-service', 'DENIALS_AND_MUTATIONS',
 1, now(), now()),
('user-profile-create', 'USER', '/api/v1/users/me', 'POST', 'http://user-service:8081', 0,
 '/api/v1/users/me', '/internal/v1/users/me', 110, TRUE,
 'JWT', '', 'profile:write', FALSE, 1000, 3000, FALSE, 1, '', TRUE, 'user-service', 'DENIALS_AND_MUTATIONS',
 1, now(), now()),
('user-profile-read', 'USER', '/api/v1/users/me', 'GET', 'http://user-service:8081', 0,
 '/api/v1/users/me', '/internal/v1/users/me', 111, TRUE,
 'JWT', '', 'profile:read', FALSE, 1000, 3000, TRUE, 2, 'GET', TRUE, 'user-service', 'DENIALS_AND_MUTATIONS',
 1, now(), now()),
('user-profile-update', 'USER', '/api/v1/users/me', 'PATCH', 'http://user-service:8081', 0,
 '/api/v1/users/me', '/internal/v1/users/me', 112, TRUE,
 'JWT', '', 'profile:write', FALSE, 1000, 3000, FALSE, 1, '', TRUE, 'user-service', 'DENIALS_AND_MUTATIONS',
 1, now(), now()),
('admin-users-list', 'ADMIN', '/api/v1/backoffice/users', 'GET', 'http://user-service:8081', 0,
 '/api/v1/backoffice/users', '/internal/v1/admin/users', 120, TRUE,
 'JWT', 'USER_ADMIN', '', FALSE, 1000, 3000, TRUE, 2, 'GET', TRUE, 'user-service', 'DENIALS_AND_MUTATIONS',
 1, now(), now()),
('admin-users-enable', 'ADMIN', '/api/v1/backoffice/users/*/enable', 'POST', 'http://user-service:8081', 0,
 '/api/v1/backoffice/users/(?<id>[^/]+)/enable', '/internal/v1/admin/users/${id}/enable', 121, TRUE,
 'JWT', 'USER_ADMIN', '', FALSE, 1000, 3000, FALSE, 1, '', TRUE, 'user-service', 'DENIALS_AND_MUTATIONS',
 1, now(), now()),
('admin-users-disable', 'ADMIN', '/api/v1/backoffice/users/*/disable', 'POST', 'http://user-service:8081', 0,
 '/api/v1/backoffice/users/(?<id>[^/]+)/disable', '/internal/v1/admin/users/${id}/disable', 122, TRUE,
 'JWT', 'USER_ADMIN', '', FALSE, 1000, 3000, FALSE, 1, '', TRUE, 'user-service', 'DENIALS_AND_MUTATIONS',
 1, now(), now()),
('admin-users-delete', 'ADMIN', '/api/v1/backoffice/users/*', 'DELETE', 'http://user-service:8081', 0,
 '/api/v1/backoffice/users/(?<id>[^/]+)', '/internal/v1/admin/users/${id}', 123, TRUE,
 'JWT', 'USER_ADMIN', '', FALSE, 1000, 3000, FALSE, 1, '', TRUE, 'user-service', 'DENIALS_AND_MUTATIONS',
 1, now(), now()),
('orders-list', 'USER', '/api/v1/orders', 'GET', 'http://order-service:8082', 0,
 '/api/v1/orders', '/internal/v1/orders', 200, TRUE,
 'JWT', '', 'orders:read', FALSE, 1000, 3000, TRUE, 2, 'GET', TRUE, 'order-service', 'DENIALS_AND_MUTATIONS',
 1, now(), now()),
('orders-create', 'USER', '/api/v1/orders', 'POST', 'http://order-service:8082', 0,
 '/api/v1/orders', '/internal/v1/orders', 201, TRUE,
 'JWT', '', 'orders:write', FALSE, 1000, 3000, FALSE, 1, '', TRUE, 'order-service', 'DENIALS_AND_MUTATIONS',
 1, now(), now()),
('orders-cancel', 'USER', '/api/v1/orders/*/cancel', 'POST', 'http://order-service:8082', 0,
 '/api/v1/orders/(?<id>[^/]+)/cancel', '/internal/v1/orders/${id}/cancel', 202, TRUE,
 'JWT', '', 'orders:write', FALSE, 1000, 3000, FALSE, 1, '', TRUE, 'order-service', 'DENIALS_AND_MUTATIONS',
 1, now(), now()),
('orders-get', 'USER', '/api/v1/orders/*', 'GET', 'http://order-service:8082', 0,
 '/api/v1/orders/(?<id>[^/]+)', '/internal/v1/orders/${id}', 203, TRUE,
 'JWT', '', 'orders:read', FALSE, 1000, 3000, TRUE, 2, 'GET', TRUE, 'order-service', 'DENIALS_AND_MUTATIONS',
 1, now(), now()),
('admin-orders-list', 'ADMIN', '/api/v1/backoffice/orders', 'GET', 'http://order-service:8082', 0,
 '/api/v1/backoffice/orders', '/internal/v1/admin/orders', 210, TRUE,
 'JWT', 'ORDER_ADMIN', '', FALSE, 1000, 3000, TRUE, 2, 'GET', TRUE, 'order-service', 'DENIALS_AND_MUTATIONS',
 1, now(), now()),
('admin-orders-update', 'ADMIN', '/api/v1/backoffice/orders/*', 'PATCH', 'http://order-service:8082', 0,
 '/api/v1/backoffice/orders/(?<id>[^/]+)', '/internal/v1/admin/orders/${id}', 211, TRUE,
 'JWT', 'ORDER_ADMIN', '', FALSE, 1000, 3000, FALSE, 1, '', TRUE, 'order-service', 'DENIALS_AND_MUTATIONS',
 1, now(), now());
