package com.omar.sentra.order.config;

import io.swagger.v3.oas.models.Components;
import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.headers.Header;
import io.swagger.v3.oas.models.info.Contact;
import io.swagger.v3.oas.models.info.Info;
import io.swagger.v3.oas.models.info.License;
import io.swagger.v3.oas.models.media.ArraySchema;
import io.swagger.v3.oas.models.media.IntegerSchema;
import io.swagger.v3.oas.models.media.Schema;
import io.swagger.v3.oas.models.media.StringSchema;
import io.swagger.v3.oas.models.parameters.Parameter;
import io.swagger.v3.oas.models.responses.ApiResponse;
import io.swagger.v3.oas.models.responses.ApiResponses;
import io.swagger.v3.oas.models.security.SecurityRequirement;
import io.swagger.v3.oas.models.servers.Server;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.springdoc.core.customizers.OpenApiCustomizer;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * Publishes and completes the internal order-service OpenAPI contract.
 */
@Configuration
public class OpenApiConfiguration {

    /**
     * Creates internal service metadata and shared response headers.
     *
     * @param properties typed limits
     * @return OpenAPI model
     */
    @Bean
    OpenAPI orderServiceOpenApi(OrderServiceProperties properties) {
        return new OpenAPI()
                .info(new Info()
                        .title("Sentra Order Service Internal API")
                        .version("1.0.0")
                        .description("""
                                Internal order API consumed by Sentra Gateway. External JWT
                                authentication is performed by the gateway. This service performs
                                defense-in-depth trusted-context, ownership, scope, role, and route
                                validation. Direct access from untrusted clients is unsupported.

                                X-Sentra-* parameters are reserved internal headers generated by
                                the gateway after stripping client-supplied values. They are not a
                                standalone external authentication mechanism.
                                """)
                        .contact(new Contact().name("Sentra Platform Engineering"))
                        .license(new License().name("Apache License 2.0").identifier("Apache-2.0")))
                .servers(List.of(new Server()
                        .url("http://order-service:8082")
                        .description("Internal service network")))
                .security(List.of(new SecurityRequirement()))
                .components(new Components().addHeaders(
                        "XRequestId",
                        new Header()
                                .description("Approved request correlation identifier")
                                .required(true)
                                .schema(new StringSchema()
                                        .minLength(1)
                                        .maxLength(properties.gateway().requestIdMaxLength()))));
    }

    /**
     * Adds shared trusted headers, correlation headers, and runtime-configured
     * schema constraints to every documented operation.
     *
     * @param properties typed service limits
     * @return contract customizer
     */
    @Bean
    OpenApiCustomizer orderServiceContractCustomizer(OrderServiceProperties properties) {
        return openApi -> {
            if (openApi == null || openApi.getPaths() == null) {
                return;
            }
            openApi.getPaths().forEach((path, pathItem) -> pathItem.readOperations().forEach(operation -> {
                boolean admin = path.startsWith("/internal/v1/admin/");
                addTrustedHeaders(operation.getParameters(), operation::setParameters, admin, properties);
                specializeTrustedHeaders(operation);
                ApiResponses responses = operation.getResponses();
                if (responses != null) {
                    responses.values().stream()
                            .filter(Objects::nonNull)
                            .forEach(OpenApiConfiguration::addCorrelationHeader);
                }
            }));
            applyConfiguredSchemaLimits(openApi, properties);
        };
    }

    private static void addTrustedHeaders(
            List<Parameter> existing,
            java.util.function.Consumer<List<Parameter>> setter,
            boolean admin,
            OrderServiceProperties properties) {
        List<Parameter> parameters = existing == null
                ? new ArrayList<>()
                : new ArrayList<>(existing);
        add(parameters, header(
                "X-Sentra-Request-Id",
                true,
                "Gateway-approved visible ASCII request ID",
                new StringSchema().minLength(1).maxLength(properties.gateway().requestIdMaxLength())
                        .pattern("^[!-~]+$"),
                "8e3a95b8-6674-423e-83e6-0df84c2d66d0"));
        add(parameters, header(
                "X-Sentra-Subject",
                true,
                "Validated JWT subject; ownership is never accepted from client data",
                new StringSchema().minLength(1).maxLength(properties.gateway().subjectMaxLength()),
                admin ? "sentra-admin" : "sentra-user-omar"));
        add(parameters, header(
                "X-Sentra-Actor-Type",
                true,
                "Trusted actor type; USER is required",
                new StringSchema()._enum(List.of("USER")),
                "USER"));
        add(parameters, header(
                "X-Sentra-Tenant-Id",
                false,
                "Optional exact trusted tenant partition",
                new StringSchema().minLength(1).maxLength(properties.gateway().tenantIdMaxLength()),
                "tenant-demo"));
        add(parameters, header(
                "X-Sentra-Scopes",
                !admin,
                admin ? "Optional gateway escaped scope list" : "Escaped list containing orders:read or orders:write",
                new StringSchema().minLength(1).maxLength(properties.gateway().trustedHeaderMaxLength()),
                admin ? null : "orders:read"));
        add(parameters, header(
                "X-Sentra-Roles",
                admin,
                admin ? "Escaped list containing ORDER_ADMIN" : "Optional gateway escaped role list",
                new StringSchema().minLength(1).maxLength(properties.gateway().trustedHeaderMaxLength()),
                admin ? "ORDER_ADMIN" : null));
        add(parameters, header(
                "X-Sentra-Route-Id",
                true,
                "Exact route identity for the selected operation",
                new StringSchema().minLength(1).maxLength(128),
                admin ? "admin-orders-list" : "orders-list"));
        add(parameters, header(
                "X-Sentra-Source-Ip",
                false,
                "Optional canonical source IPv4 or IPv6 literal",
                new StringSchema().minLength(2).maxLength(64),
                "203.0.113.10"));
        add(parameters, header(
                "X-Sentra-Auth-Time",
                false,
                "Optional gateway-validated RFC 3339 authentication time",
                new StringSchema().format("date-time"),
                "2026-06-15T12:00:00Z"));
        add(parameters, header(
                "X-Sentra-Client-Id",
                false,
                "Prohibited for USER order operations",
                new StringSchema().maxLength(properties.gateway().trustedHeaderMaxLength()),
                null).deprecated(true));
        setter.accept(parameters);
    }

    private static Parameter header(
            String name,
            boolean required,
            String description,
            Schema<?> schema,
            String example) {
        Parameter parameter = new Parameter()
                .name(name)
                .in("header")
                .required(required)
                .description(description)
                .schema(schema);
        if (example != null) {
            parameter.setExample(example);
        }
        return parameter;
    }

    private static void add(List<Parameter> parameters, Parameter parameter) {
        boolean exists = parameters.stream()
                .anyMatch(current -> parameter.getName().equals(current.getName())
                        && parameter.getIn().equals(current.getIn()));
        if (!exists) {
            parameters.add(parameter);
        }
    }

    private static void specializeTrustedHeaders(io.swagger.v3.oas.models.Operation operation) {
        String routeId = switch (operation.getOperationId()) {
            case "listCurrentUserOrders" -> "orders-list";
            case "getCurrentUserOrder" -> "orders-get";
            case "createCurrentUserOrder" -> "orders-create";
            case "listOrdersAsAdministrator" -> "admin-orders-list";
            default -> null;
        };
        if (routeId == null || operation.getParameters() == null) {
            return;
        }
        operation.getParameters().stream()
                .filter(parameter -> "X-Sentra-Route-Id".equals(parameter.getName()))
                .findFirst()
                .ifPresent(parameter -> {
                    parameter.setExample(routeId);
                    parameter.setSchema(new StringSchema()._enum(List.of(routeId)).maxLength(128));
                });
        if ("createCurrentUserOrder".equals(operation.getOperationId())) {
            setExample(operation.getParameters(), "X-Sentra-Scopes", "orders:write");
        } else if (!"listOrdersAsAdministrator".equals(operation.getOperationId())) {
            setExample(operation.getParameters(), "X-Sentra-Scopes", "orders:read");
        }
    }

    private static void setExample(List<Parameter> parameters, String name, String example) {
        parameters.stream()
                .filter(parameter -> name.equals(parameter.getName()))
                .findFirst()
                .ifPresent(parameter -> parameter.setExample(example));
    }

    private static void addCorrelationHeader(ApiResponse response) {
        if (response.getHeaders() == null || !response.getHeaders().containsKey("X-Request-Id")) {
            response.addHeaderObject(
                    "X-Request-Id",
                    new Header().$ref("#/components/headers/XRequestId"));
        }
    }

    @SuppressWarnings("rawtypes")
    private static void applyConfiguredSchemaLimits(
            OpenAPI openApi,
            OrderServiceProperties properties) {
        Components components = openApi.getComponents();
        Map<String, Schema> schemas = components == null || components.getSchemas() == null
                ? Map.of()
                : components.getSchemas();
        Schema<?> create = schemas.get("CreateOrderRequest");
        Schema<?> items = property(create, "items");
        if (items instanceof ArraySchema array) {
            array.setMaxItems(properties.limits().maxItemsPerOrder());
        }
        Schema<?> item = schemas.get("CreateOrderItemRequest");
        Schema<?> sku = property(item, "sku");
        if (sku != null) {
            sku.setMaxLength(properties.limits().maxSkuLength());
        }
        Schema<?> quantity = property(item, "quantity");
        if (quantity instanceof IntegerSchema integer) {
            integer.setMaximum(java.math.BigDecimal.valueOf(properties.limits().maxItemQuantity()));
        }
        Schema<?> error = schemas.get("ApiError");
        Schema<?> details = property(error, "details");
        if (details instanceof ArraySchema array) {
            array.setMaxItems(properties.limits().maxErrorDetails());
        }
    }

    private static Schema<?> property(Schema<?> schema, String name) {
        return schema == null || schema.getProperties() == null
                ? null
                : schema.getProperties().get(name);
    }
}
