FROM docker.io/library/maven:3.9.12-eclipse-temurin-25 AS build
WORKDIR /workspace
COPY pom.xml .
COPY .mvn .mvn
COPY mvnw mvnw
COPY mvnw.cmd mvnw.cmd
RUN mvn -B -ntp dependency:go-offline
COPY src src
RUN mvn -B -ntp clean verify

FROM docker.io/library/eclipse-temurin:25-jre
RUN apt-get update \
    && apt-get install -y --no-install-recommends curl \
    && rm -rf /var/lib/apt/lists/*
RUN useradd --system --uid 10003 --create-home sentra
WORKDIR /app
COPY --from=build /workspace/target/payment-service-1.0.0-SNAPSHOT.jar /app/payment-service.jar
USER 10003
EXPOSE 8083
ENTRYPOINT ["java", "-XX:MaxRAMPercentage=75.0", "-Djava.security.egd=file:/dev/urandom", "-jar", "/app/payment-service.jar"]
